import { image } from "../public/images/image-007.jpg";
const specifications = {
  data: [
    {
      label: "Pages",
      value: "pages",
      variations: [
        {
          label: "140",
          value: "140",
        },
        {
          label: "172",
          value: "172",
        },
      ],
    },
    {
      label: "Size",
      value: "size",
      variations: [
        {
          label: "Long Notebook (29.7 x 21 cm)",
          value: "longBook",
        },
        {
          label: "Short Notebook (24 x 18 cm)",
          value: "shortBook",
        },
      ],
    },
    {
      label: "Binding",
      value: "binding",
      variations: [
        {
          label: "Spiral",
          value: "spiral",
        },
        {
          label: "Center Stapled",
          value: "centerStapled",
        },
      ],
    },
    {
      label: "Ruling",
      value: "ruling",
      variations: [
        {
          label: "Ruled",
          value: "ruled",
        },
        {
          label: "Unruled",
          value: "unruled",
        },
      ],
    },
    {
      label: "Quantity",
      value: "quantity",
      variations: [
        {
          label: "6",
          value: "6",
        },
        {
          label: "12",
          value: "12",
        },
        {
          label: "18",
          value: "18",
        },
        {
          label: "24",
          value: "24",
        },
        {
          label: "32",
          value: "32",
        },
      ],
    },
  ],
  defaultValues: {
    pages: "140",
    size: "longBook",
    binding: "spiral",
    ruling: "unruled",
    quantity: "6",
  },
};

const quickTips = [
  {
    id: 1,
    title:
      "Image size should not exceed 10MB & video size should not exceed 100MB",
  },
  {
    id: 2,
    title:
      "Please avoid uploading images of celebrities, sports stars, TV characters, cartoon characters or images for which you do not own the copyrights.",
  },
  {
    id: 3,
    title:
      "Please ensure to resize the images as necessary to fit the canvas. You can open the canvas & resize the image.",
  },
  {
    id: 4,
    title:
      "Please avoid placing any text too close to the border since there are slight chances that it might get cut.",
  },

  {
    id: 5,
    title:
      "Please Check final preview to see if the designs are placed as you wish.",
  },
];

const designTemplates = [
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjI0OQ==",
    name: "Travel - 11",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-007.jpg?alt=media&token=17bb1b35-796f-433e-b733-16a403d8207e",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjI0OA==",
    name: "Travel - 10",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-008.jpg?alt=media&token=1c231eeb-3aa0-4ff0-b199-642fc7850286",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjI0Nw==",
    name: "Travel - 09",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-009.jpg?alt=media&token=2ffb24f8-4556-4acc-9e00-f28a8a1618fa",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjcz",
    name: "Travel - 08",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-010.jpg?alt=media&token=1a96a9ba-86b6-4b7a-ae94-cbfe9365faab",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjcy",
    name: "Travel - 07",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-011.jpg?alt=media&token=ea49af28-7730-4bca-b884-4359cfc4a7a2",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjcx",
    name: "Travel - 06",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-012.jpg?alt=media&token=91ef7875-e4c1-4ea9-9b9c-cf923b9e3e25",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjcw",
    name: "Travel - 05",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-013.jpg?alt=media&token=cfe71691-4227-41d9-bc72-ccc0b4539371",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY5",
    name: "Travel - 04",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-014.jpg?alt=media&token=4f701b46-f8ca-4def-889a-7e6c2e50bc34",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY4",
    name: "Travel - 03",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-015.jpg?alt=media&token=0ada83d6-cd3f-4f9e-b477-c5d0edb3bf06",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },

  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY31",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-017.jpg?alt=media&token=45a04f22-aabd-47b9-a4e7-2ee440009e93",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=1",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY3",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-016.jpg?alt=media&token=170e1a53-e0ec-494d-988d-a5965059efaf",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY32",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-018.jpg?alt=media&token=2416b368-41db-4747-b270-88a1f682b4bc",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=2",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY33",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-019.jpg?alt=media&token=3c86adcd-6ab4-4681-a66d-61bf61092fdc",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=3",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY34",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-020.jpg?alt=media&token=f18c99f0-9978-4564-b91d-34d0b801330c",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=4",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY35",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-021.jpg?alt=media&token=0e5a068a-d643-43b7-8dd0-ab99d14879d3",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=5",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY36",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-023.jpg?alt=media&token=0a0cd73b-23e5-48ea-8919-662df07f0f55",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=6",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY37",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-024.jpg?alt=media&token=520806e0-f887-4373-9ce4-27c3ea81561c",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ7=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY38",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-025.jpg?alt=media&token=cf78df3c-4dec-4391-bf62-30bd6a1815bf",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=8",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY39",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-026.jpg?alt=media&token=96bd0f9a-ad96-47c2-8bcb-5290e9ca2846",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=9",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY312",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-027.jpg?alt=media&token=bdbb7302-0053-4086-912f-f1abdd916a49",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=12",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY311",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-028.jpg?alt=media&token=059a3fa5-a607-4c5b-9cb2-cf33cf92e977",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=11",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY323",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-029.jpg?alt=media&token=efa16ac9-36e6-4613-9543-2636b333f3ad",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=23",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY332",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-030.jpg?alt=media&token=35abf8c6-5a55-4619-b26a-4a3657364386",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=32",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY3234",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-031.jpg?alt=media&token=e8bd373b-e1c0-4c88-8a65-d3aaf6f3e883",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=43",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY345",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "https://firebasestorage.googleapis.com/v0/b/navneet-3d437.appspot.com/o/image-032.jpg?alt=media&token=3a154b69-177a-4462-8c9e-50d386039149",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=75f",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
];
export { specifications, designTemplates, quickTips };
