import { image } from "../public/images/image-007.jpg";
const specifications = {
  data: [
    {
      label: "Pages",
      value: "pages",
      variations: [
        {
          label: "140",
          value: "140",
        },
        {
          label: "172",
          value: "172",
        },
      ],
    },
    {
      label: "Size",
      value: "size",
      variations: [
        {
          label: "Long Notebook (29.7 x 21 cm)",
          value: "longBook",
        },
        {
          label: "Short Notebook (24 x 18 cm)",
          value: "shortBook",
        },
      ],
    },
    {
      label: "Binding",
      value: "binding",
      variations: [
        {
          label: "Spiral",
          value: "spiral",
        },
        {
          label: "Center Stapled",
          value: "centerStapled",
        },
      ],
    },
    {
      label: "Ruling",
      value: "ruling",
      variations: [
        {
          label: "Ruled",
          value: "ruled",
        },
        {
          label: "Unruled",
          value: "unruled",
        },
      ],
    },
    {
      label: "Quantity",
      value: "quantity",
      variations: [
        {
          label: "6",
          value: "6",
        },
        {
          label: "12",
          value: "12",
        },
        {
          label: "18",
          value: "18",
        },
        {
          label: "24",
          value: "24",
        },
        {
          label: "32",
          value: "32",
        },
      ],
    },
  ],
  defaultValues: {
    pages: "140",
    size: "longBook",
    binding: "spiral",
    ruling: "unruled",
    quantity: "6",
  },
};

const quickTips = [
  {
    id: 1,
    title:
      "Image size should not exceed 10MB & video size should not exceed 100MB",
  },
  {
    id: 2,
    title:
      "Please avoid uploading images of celebrities, sports stars, TV characters, cartoon characters or images for which you do not own the copyrights.",
  },
  {
    id: 3,
    title:
      "Please ensure to resize the images as necessary to fit the canvas. You can open the canvas & resize the image.",
  },
  {
    id: 4,
    title:
      "Please avoid placing any text too close to the border since there are slight chances that it might get cut.",
  },

  {
    id: 5,
    title:
      "Please Check final preview to see if the designs are placed as you wish.",
  },
];

const designTemplates = [
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjI0OQ==",
    name: "Travel - 11",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-007.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjI0OA==",
    name: "Travel - 10",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-008.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjI0Nw==",
    name: "Travel - 09",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-009.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjcz",
    name: "Travel - 08",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-010.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjcy",
    name: "Travel - 07",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-011.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjcx",
    name: "Travel - 06",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-012.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjcw",
    name: "Travel - 05",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-013.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY5",
    name: "Travel - 04",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-014.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY4",
    name: "Travel - 03",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-015.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY3",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-016.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY31",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-017.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=1",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY32",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-018.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=2",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY33",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-019.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=3",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY34",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-020.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=4",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY35",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-021.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=5",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY36",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-023.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=6",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY37",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-024.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ7=",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY38",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-025.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=8",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY39",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-026.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=9",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY312",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-027.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=12",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY311",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-028.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=11",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY323",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-029.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=23",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY332",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-030.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=32",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY3234",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-031.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=43",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
  {
    id: "RGVzaWduVGVtcGxhdGVOb2RlOjY345",
    name: "Travel - 02",
    price: null,
    discountedPrice: null,
    isAr: false,
    templateType: "LICENSED_DESIGN",
    url: "/images/image-032.jpg",
    category: {
      id: "RGVzaWduQ2F0ZWdvcnlOb2RlOjQ=75f",
      name: "Travel",
      price: "10.00",
      discountedPrice: "0.00",
    },
  },
];
export { specifications, designTemplates, quickTips };
